services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/.venv
      - /Users/koji/.config/gcloud:/root/.config/gcloud:ro
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      GCS_SPEECH_BUCKET: ${GCS_SPEECH_BUCKET}
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
