[project]
name = "backend"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "psycopg2-binary",
    "google-api-python-client>=2.174.0",
    "youtube-transcript-api",
    "pytest",
    "pytest-mock",
    "ipykernel>=6.30.1",
]
